Updation on Skills Stack (#10)

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -4,17 +4,26 @@
 echo '🙂 Please be patient, this may take a while...⏳'
 
 echo '👷🏻⚒️ Styling your code before committing...'
-yarn format-write
+pnpm format-write
 
 echo '👮🏻🔎 Checking Styles in your code before committing...'
-yarn format-check
+pnpm format-check
 
 echo '👮🏻🚨 Making sure no linting errors in your code before committing...'
-yarn lint ||
+pnpm lint ||
 (
 
     echo '⚠️ Oops❗, you have a problem in your code. Check linter ❌⚒️
-          💡Run yarn lint, add changes & try committing again.👍🏻';
+          💡Run pnpm lint, add changes & try committing again.👍🏻';
+    false;
+)
+
+echo '🛞🚨 Making sure no type errors in your code before committing...'
+pnpm type-check ||
+(
+
+    echo '⚠️ Oops❗, you have a problem in your code. Check types ❌⚒️
+          💡Run pnpm type-check, add changes & try committing again.👍🏻';
     false;
 )
 
